name: cash_register
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get_it:
  flutter_bloc:
  equatable:
  dartz:
  connectivity_plus:
  http:
  shared_preferences:
  supabase_flutter: ^2.8.0
  json_annotation: ^4.9.0
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  package_info_plus: 
  adaptive_theme:
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  file_picker: ^8.1.4
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  open_filex: ^4.3.2
  enough_convert: ^1.6.0
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  build_runner:
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  generate: true
  
  # Assets для Cashalot ключів
  assets:
    - assets/cashalot_keys/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo/windows_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"